[package]
name = "doom-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
serde_derive = "1.0.130"
rmp-serde = "0.15.5"
sdl2 = "0.34.5"
vek = "0.15.1"